---
 deployment:
  tasks:
    - export DEPLOYPATH=/home2/fullcdhk/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R _img $DEPLOYPATH
    - /bin/cp -R _css $DEPLOYPATH
    # Add _audio and _css if needed
